# Generated by Django 6.1.1 on 2026-09-20 10:21
# Generated by Django 6.1.1 on 2026-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0003_availabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
