# Generated by Django 6.1.1 on 2026-09-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0004_profile_onboarding_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_completed',
        ),
    ]
