# Generated by Django 6.1.1 on 2026-09-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0005_mark_existing_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_session_duration_minutes',
            field=models.PositiveIntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=120),
        ),
    ]
