# Generated by Django 6.1.1 on 2026-09-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0007_alter_profile_max_session_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
