# Generated by Django 6.1.1 on 2026-09-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0008_profile_rating_average_profile_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Designates whether the user wishes to receive email notifications.'),
        ),
    ]
