# Generated by Django 6.1.1 on 2026-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0014_question_bank_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillquizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10),
        ),
    ]
