# Generated by Django 6.1.1 on 2026-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0015_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillquizattempt',
            name='review',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
