# Generated by Django 6.1.1 on 2026-09-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillswapmeeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='skillswapmeeting',
            name='room_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillswapmeeting',
            name='token_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skillswapmeeting',
            name='token_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
