# Generated by Django 6.1.1 on 2026-09-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_skillswapmeeting_room_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillswapmeeting',
            name='room_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='skillswapmeeting',
            name='token_a',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='skillswapmeeting',
            name='token_b',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
