# Generated by Django 6.1.1 on 2026-09-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('meetings', '0004_alter_skillswapmeeting_room_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('room_url', models.URLField(blank=True, default='')),
                ('room_name', models.CharField(blank=True, default='', max_length=255)),
                ('token_sender', models.CharField(blank=True, default='', max_length=500)),
                ('token_receiver', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='matching.matchrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='SkillSwapMeeting',
        ),
    ]
