# Generated by Django 6.1.1 on 2026-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_delete_skillswapmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='room_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='token_receiver',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='token_sender',
            field=models.TextField(blank=True, default=''),
        ),
    ]
