# Generated by Django 6.1.1 on 2026-09-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_matchrequest_receiver_requested_end_time_and_more'),
        ('meetings', '0007_meetingrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='session_type',
            field=models.CharField(choices=[('REQUESTED_SKILL', 'Requested Skill'), ('RETURN_SKILL', 'Return Skill')], default='REQUESTED_SKILL', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='matching.matchrequest'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('request', 'session_type'), name='unique_request_session_type'),
        ),
    ]
