# Generated by Django 6.1.1 on 2026-09-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
