# Generated by Django 6.1.1 on 2026-09-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchrequest_rejection_reason'),
        ('skillmatch', '0007_alter_profile_max_session_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='receiver_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_match_requests', to='skillmatch.skill'),
        ),
    ]
