# Generated by Django 6.1.1 on 2026-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_matchrequest_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='source',
            field=models.CharField(choices=[('match', 'Matching Page'), ('browse', 'Skill Browse')], max_length=10),
        ),
    ]
