# Generated by Django 6.1.1 on 2026-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_alter_matchrequest_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='source',
            field=models.CharField(choices=[('matches', 'Matching Page'), ('skillbrowse', 'Skill Browse')], default='matches', max_length=20),
        ),
    ]
