# Generated by Django 6.1.1 on 2026-09-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_alter_matchrequest_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrequest',
            name='source',
        ),
    ]
