# Generated by Django 6.1.1 on 2026-09-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_matchrequest_requested_times'),
        ('skillmatch', '0013_skill_approval_quiz_abandoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='receiver_requested_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='receiver_requested_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='receiver_selected_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_selected_match_requests', to='skillmatch.availabilityslot'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULING', 'Scheduling'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
