# Generated by Django 6.1.1 on 2026-10-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_matchrequest_receiver_requested_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULING', 'Scheduling'), ('ACCEPTED', 'Accepted'), ('CONFIRMING', 'Waiting for return confirmation'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
